create table "public"."address" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" character varying not null,
    "street" character varying not null,
    "zip_code" character varying not null,
    "latitude" double precision,
    "longitude" double precision,
    "is_default" boolean not null default true,
    "user_id" uuid not null
);


create table "public"."billing" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "total_amount" real not null,
    "fees" real not null,
    "fliiinker_rate" real not null
);


create table "public"."channel" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" character varying not null
);


create table "public"."channel_user_mtm" (
    "channel_id" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null
);


create table "public"."customer_rating" (
    "created_at" timestamp with time zone not null default now(),
    "rating" smallint not null,
    "comment" character varying,
    "comment_is_visible" boolean not null default false,
    "customer_id" uuid not null,
    "fliiinker_id" uuid not null default gen_random_uuid()
);


create table "public"."fliiinker_config" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "radius_max" smallint not null,
    "status" character varying not null,
    "active_days" character varying not null
);


create table "public"."fliiinker_profile" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "images" bigint,
    "description" character varying,
    "degree" character varying,
    "tagline" character varying,
    "radius_max" smallint not null,
    "status" character varying not null,
    "fliiinker_config_id" bigint not null,
    "public_profile_id" uuid
);


create table "public"."fliiinker_rating" (
    "created_at" timestamp with time zone not null default now(),
    "rating" smallint not null,
    "comment" character varying,
    "comment_is_visible" boolean not null default false,
    "fliiinker_id" uuid not null,
    "customer_id" uuid not null
);


create table "public"."fliiinker_service_mtm" (
    "service_id" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "is_active" boolean not null default false,
    "hourly_rate" smallint not null,
    "description" character varying,
    "options" jsonb,
    "fliiinker_id" uuid not null
);


create table "public"."fliiinker_service_rating" (
    "service_id" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "rating" smallint not null,
    "comment" character varying,
    "comment_is_visible" boolean not null default false,
    "fliiinker_id" uuid not null,
    "customer_id" uuid not null
);


create table "public"."linking" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "status" character varying not null,
    "search_id" bigint not null,
    "customer_id" uuid not null,
    "fliiinker_id" uuid not null
);


create table "public"."linking_event" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" character varying not null,
    "linking_id" bigint not null
);


create table "public"."message_chat" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "message" character varying not null,
    "channel_id" bigint not null,
    "sender_id" uuid not null
);


create table "public"."order" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "start_date" timestamp with time zone not null,
    "end_date" timestamp with time zone not null,
    "status" character varying not null,
    "order_metadata_id" bigint not null,
    "service_id" bigint not null,
    "billing_id" bigint,
    "channel_id" bigint,
    "customer_id" uuid not null,
    "fliiinker_id" uuid not null
);


create table "public"."order_metadata" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "customer_address_id" bigint not null,
    "fliiinker_address_id" bigint not null,
    "start_date" timestamp with time zone not null,
    "end_date" timestamp with time zone not null,
    "service_duration" real not null
);


create table "public"."public_profile" (
    "created_at" timestamp with time zone not null default now(),
    "email" character varying not null,
    "id" uuid not null,
    "email_confirmed_at" timestamp with time zone,
    "phone" text,
    "phone_confirmed_at" timestamp with time zone,
    "last_name" character varying,
    "first_name" character varying
);


create table "public"."search" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "status" character varying,
    "service_id" bigint
);


create table "public"."service" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" character varying not null,
    "logo" character varying not null,
    "description" character varying not null,
    "body" character varying
);


create table "public"."user_search_mtm" (
    "search_id" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "customer_id" uuid not null
);


CREATE UNIQUE INDEX address_pkey ON public.address USING btree (id);

CREATE UNIQUE INDEX billing_pkey ON public.billing USING btree (id);

CREATE UNIQUE INDEX channel_pkey ON public.channel USING btree (id);

CREATE UNIQUE INDEX channel_user_mtm_pkey ON public.channel_user_mtm USING btree (channel_id, user_id);

CREATE UNIQUE INDEX fliiinker_config_pkey ON public.fliiinker_config USING btree (id);

CREATE UNIQUE INDEX fliiinker_profile_pkey ON public.fliiinker_profile USING btree (id);

CREATE UNIQUE INDEX fliiinker_service_rating_pkey ON public.fliiinker_service_rating USING btree (service_id, fliiinker_id, customer_id);

CREATE UNIQUE INDEX linking_events_pkey ON public.linking_event USING btree (id);

CREATE UNIQUE INDEX linking_pkey ON public.linking USING btree (id);

CREATE UNIQUE INDEX message_chat_pkey ON public.message_chat USING btree (id);

CREATE UNIQUE INDEX order_metadata_pkey ON public.order_metadata USING btree (id);

CREATE UNIQUE INDEX order_pkey ON public."order" USING btree (id);

CREATE UNIQUE INDEX public_profile_pkey ON public.public_profile USING btree (id);

CREATE UNIQUE INDEX search_pkey ON public.search USING btree (id);

CREATE UNIQUE INDEX service_pkey ON public.service USING btree (id);

CREATE UNIQUE INDEX user_search_mtm_pkey ON public.user_search_mtm USING btree (search_id, customer_id);

alter table "public"."address" add constraint "address_pkey" PRIMARY KEY using index "address_pkey";

alter table "public"."billing" add constraint "billing_pkey" PRIMARY KEY using index "billing_pkey";

alter table "public"."channel" add constraint "channel_pkey" PRIMARY KEY using index "channel_pkey";

alter table "public"."channel_user_mtm" add constraint "channel_user_mtm_pkey" PRIMARY KEY using index "channel_user_mtm_pkey";

alter table "public"."fliiinker_config" add constraint "fliiinker_config_pkey" PRIMARY KEY using index "fliiinker_config_pkey";

alter table "public"."fliiinker_profile" add constraint "fliiinker_profile_pkey" PRIMARY KEY using index "fliiinker_profile_pkey";

alter table "public"."fliiinker_service_rating" add constraint "fliiinker_service_rating_pkey" PRIMARY KEY using index "fliiinker_service_rating_pkey";

alter table "public"."linking" add constraint "linking_pkey" PRIMARY KEY using index "linking_pkey";

alter table "public"."linking_event" add constraint "linking_events_pkey" PRIMARY KEY using index "linking_events_pkey";

alter table "public"."message_chat" add constraint "message_chat_pkey" PRIMARY KEY using index "message_chat_pkey";

alter table "public"."order" add constraint "order_pkey" PRIMARY KEY using index "order_pkey";

alter table "public"."order_metadata" add constraint "order_metadata_pkey" PRIMARY KEY using index "order_metadata_pkey";

alter table "public"."public_profile" add constraint "public_profile_pkey" PRIMARY KEY using index "public_profile_pkey";

alter table "public"."search" add constraint "search_pkey" PRIMARY KEY using index "search_pkey";

alter table "public"."service" add constraint "service_pkey" PRIMARY KEY using index "service_pkey";

alter table "public"."user_search_mtm" add constraint "user_search_mtm_pkey" PRIMARY KEY using index "user_search_mtm_pkey";

alter table "public"."address" add constraint "public_address_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public_profile(id) not valid;

alter table "public"."address" validate constraint "public_address_user_id_fkey";

alter table "public"."channel_user_mtm" add constraint "public_channel_user_mtm_channel_id_fkey" FOREIGN KEY (channel_id) REFERENCES channel(id) not valid;

alter table "public"."channel_user_mtm" validate constraint "public_channel_user_mtm_channel_id_fkey";

alter table "public"."channel_user_mtm" add constraint "public_channel_user_mtm_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public_profile(id) not valid;

alter table "public"."channel_user_mtm" validate constraint "public_channel_user_mtm_user_id_fkey";

alter table "public"."customer_rating" add constraint "public_customer_rating_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES public_profile(id) not valid;

alter table "public"."customer_rating" validate constraint "public_customer_rating_customer_id_fkey";

alter table "public"."customer_rating" add constraint "public_customer_rating_fliiinker_id_fkey" FOREIGN KEY (fliiinker_id) REFERENCES public_profile(id) not valid;

alter table "public"."customer_rating" validate constraint "public_customer_rating_fliiinker_id_fkey";

alter table "public"."fliiinker_profile" add constraint "public_fliiinker_profile_fliiinker_config_id_fkey" FOREIGN KEY (fliiinker_config_id) REFERENCES fliiinker_config(id) not valid;

alter table "public"."fliiinker_profile" validate constraint "public_fliiinker_profile_fliiinker_config_id_fkey";

alter table "public"."fliiinker_rating" add constraint "public_fliiinker_rating_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES public_profile(id) not valid;

alter table "public"."fliiinker_rating" validate constraint "public_fliiinker_rating_customer_id_fkey";

alter table "public"."fliiinker_rating" add constraint "public_fliiinker_rating_fliiinker_id_fkey" FOREIGN KEY (fliiinker_id) REFERENCES public_profile(id) not valid;

alter table "public"."fliiinker_rating" validate constraint "public_fliiinker_rating_fliiinker_id_fkey";

alter table "public"."fliiinker_service_mtm" add constraint "public_fliiinker_service_mtm_fliiinker_id_fkey" FOREIGN KEY (fliiinker_id) REFERENCES public_profile(id) not valid;

alter table "public"."fliiinker_service_mtm" validate constraint "public_fliiinker_service_mtm_fliiinker_id_fkey";

alter table "public"."fliiinker_service_mtm" add constraint "public_fliiinker_service_mtm_service_id_fkey" FOREIGN KEY (service_id) REFERENCES service(id) not valid;

alter table "public"."fliiinker_service_mtm" validate constraint "public_fliiinker_service_mtm_service_id_fkey";

alter table "public"."fliiinker_service_rating" add constraint "public_fliiinker_service_rating_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES public_profile(id) not valid;

alter table "public"."fliiinker_service_rating" validate constraint "public_fliiinker_service_rating_customer_id_fkey";

alter table "public"."fliiinker_service_rating" add constraint "public_fliiinker_service_rating_fliiinker_id_fkey" FOREIGN KEY (fliiinker_id) REFERENCES public_profile(id) not valid;

alter table "public"."fliiinker_service_rating" validate constraint "public_fliiinker_service_rating_fliiinker_id_fkey";

alter table "public"."linking" add constraint "public_linking_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES public_profile(id) not valid;

alter table "public"."linking" validate constraint "public_linking_customer_id_fkey";

alter table "public"."linking" add constraint "public_linking_fliiinker_id_fkey" FOREIGN KEY (fliiinker_id) REFERENCES public_profile(id) not valid;

alter table "public"."linking" validate constraint "public_linking_fliiinker_id_fkey";

alter table "public"."linking" add constraint "public_linking_search_id_fkey" FOREIGN KEY (search_id) REFERENCES search(id) not valid;

alter table "public"."linking" validate constraint "public_linking_search_id_fkey";

alter table "public"."linking_event" add constraint "public_linking_event_linking_id_fkey" FOREIGN KEY (linking_id) REFERENCES linking(id) not valid;

alter table "public"."linking_event" validate constraint "public_linking_event_linking_id_fkey";

alter table "public"."message_chat" add constraint "public_message_chat_channel_id_fkey" FOREIGN KEY (channel_id) REFERENCES channel(id) not valid;

alter table "public"."message_chat" validate constraint "public_message_chat_channel_id_fkey";

alter table "public"."message_chat" add constraint "public_message_chat_sender_id_fkey" FOREIGN KEY (sender_id) REFERENCES public_profile(id) not valid;

alter table "public"."message_chat" validate constraint "public_message_chat_sender_id_fkey";

alter table "public"."order" add constraint "public_order_billing_id_fkey" FOREIGN KEY (billing_id) REFERENCES billing(id) not valid;

alter table "public"."order" validate constraint "public_order_billing_id_fkey";

alter table "public"."order" add constraint "public_order_channel_id_fkey" FOREIGN KEY (channel_id) REFERENCES channel(id) not valid;

alter table "public"."order" validate constraint "public_order_channel_id_fkey";

alter table "public"."order" add constraint "public_order_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES public_profile(id) not valid;

alter table "public"."order" validate constraint "public_order_customer_id_fkey";

alter table "public"."order" add constraint "public_order_fliiinker_id_fkey" FOREIGN KEY (fliiinker_id) REFERENCES public_profile(id) not valid;

alter table "public"."order" validate constraint "public_order_fliiinker_id_fkey";

alter table "public"."order" add constraint "public_order_order_metadata_id_fkey" FOREIGN KEY (order_metadata_id) REFERENCES order_metadata(id) not valid;

alter table "public"."order" validate constraint "public_order_order_metadata_id_fkey";

alter table "public"."order" add constraint "public_order_service_id_fkey" FOREIGN KEY (service_id) REFERENCES service(id) not valid;

alter table "public"."order" validate constraint "public_order_service_id_fkey";

alter table "public"."order_metadata" add constraint "public_order_metadata_customer_address_id_fkey" FOREIGN KEY (customer_address_id) REFERENCES address(id) not valid;

alter table "public"."order_metadata" validate constraint "public_order_metadata_customer_address_id_fkey";

alter table "public"."order_metadata" add constraint "public_order_metadata_fliiinker_address_id_fkey" FOREIGN KEY (fliiinker_address_id) REFERENCES address(id) not valid;

alter table "public"."order_metadata" validate constraint "public_order_metadata_fliiinker_address_id_fkey";

alter table "public"."public_profile" add constraint "public_public_profile_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) not valid;

alter table "public"."public_profile" validate constraint "public_public_profile_id_fkey";

alter table "public"."search" add constraint "public_search_service_id_fkey" FOREIGN KEY (service_id) REFERENCES service(id) not valid;

alter table "public"."search" validate constraint "public_search_service_id_fkey";

alter table "public"."user_search_mtm" add constraint "public_user_search_mtm_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES public_profile(id) not valid;

alter table "public"."user_search_mtm" validate constraint "public_user_search_mtm_customer_id_fkey";

alter table "public"."user_search_mtm" add constraint "public_user_search_mtm_search_id_fkey" FOREIGN KEY (search_id) REFERENCES search(id) not valid;

alter table "public"."user_search_mtm" validate constraint "public_user_search_mtm_search_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.sync_auth_user_public_profile()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN    
    IF EXISTS (SELECT 1 FROM public.public_profile WHERE id = NEW.id) THEN
        UPDATE public.public_profile
        SET            
            email = NEW.email,
            email_confirmed_at = NEW.email_confirmed_at,
            phone = NEW.phone,
            phone_confirmed_at = NEW.phone_confirmed_at
        WHERE id = NEW.id;
    ELSE
        INSERT INTO public.public_profile (id, email, email_confirmed_at, phone, phone_confirmed_at)
        VALUES (NEW.id, NEW.email, NEW.email_confirmed_at, NEW.phone, NEW.phone_confirmed_at);
    END IF;
    RETURN NEW;
END;
$function$
;

grant delete on table "public"."address" to "anon";

grant insert on table "public"."address" to "anon";

grant references on table "public"."address" to "anon";

grant select on table "public"."address" to "anon";

grant trigger on table "public"."address" to "anon";

grant truncate on table "public"."address" to "anon";

grant update on table "public"."address" to "anon";

grant delete on table "public"."address" to "authenticated";

grant insert on table "public"."address" to "authenticated";

grant references on table "public"."address" to "authenticated";

grant select on table "public"."address" to "authenticated";

grant trigger on table "public"."address" to "authenticated";

grant truncate on table "public"."address" to "authenticated";

grant update on table "public"."address" to "authenticated";

grant delete on table "public"."address" to "service_role";

grant insert on table "public"."address" to "service_role";

grant references on table "public"."address" to "service_role";

grant select on table "public"."address" to "service_role";

grant trigger on table "public"."address" to "service_role";

grant truncate on table "public"."address" to "service_role";

grant update on table "public"."address" to "service_role";

grant delete on table "public"."billing" to "anon";

grant insert on table "public"."billing" to "anon";

grant references on table "public"."billing" to "anon";

grant select on table "public"."billing" to "anon";

grant trigger on table "public"."billing" to "anon";

grant truncate on table "public"."billing" to "anon";

grant update on table "public"."billing" to "anon";

grant delete on table "public"."billing" to "authenticated";

grant insert on table "public"."billing" to "authenticated";

grant references on table "public"."billing" to "authenticated";

grant select on table "public"."billing" to "authenticated";

grant trigger on table "public"."billing" to "authenticated";

grant truncate on table "public"."billing" to "authenticated";

grant update on table "public"."billing" to "authenticated";

grant delete on table "public"."billing" to "service_role";

grant insert on table "public"."billing" to "service_role";

grant references on table "public"."billing" to "service_role";

grant select on table "public"."billing" to "service_role";

grant trigger on table "public"."billing" to "service_role";

grant truncate on table "public"."billing" to "service_role";

grant update on table "public"."billing" to "service_role";

grant delete on table "public"."channel" to "anon";

grant insert on table "public"."channel" to "anon";

grant references on table "public"."channel" to "anon";

grant select on table "public"."channel" to "anon";

grant trigger on table "public"."channel" to "anon";

grant truncate on table "public"."channel" to "anon";

grant update on table "public"."channel" to "anon";

grant delete on table "public"."channel" to "authenticated";

grant insert on table "public"."channel" to "authenticated";

grant references on table "public"."channel" to "authenticated";

grant select on table "public"."channel" to "authenticated";

grant trigger on table "public"."channel" to "authenticated";

grant truncate on table "public"."channel" to "authenticated";

grant update on table "public"."channel" to "authenticated";

grant delete on table "public"."channel" to "service_role";

grant insert on table "public"."channel" to "service_role";

grant references on table "public"."channel" to "service_role";

grant select on table "public"."channel" to "service_role";

grant trigger on table "public"."channel" to "service_role";

grant truncate on table "public"."channel" to "service_role";

grant update on table "public"."channel" to "service_role";

grant delete on table "public"."channel_user_mtm" to "anon";

grant insert on table "public"."channel_user_mtm" to "anon";

grant references on table "public"."channel_user_mtm" to "anon";

grant select on table "public"."channel_user_mtm" to "anon";

grant trigger on table "public"."channel_user_mtm" to "anon";

grant truncate on table "public"."channel_user_mtm" to "anon";

grant update on table "public"."channel_user_mtm" to "anon";

grant delete on table "public"."channel_user_mtm" to "authenticated";

grant insert on table "public"."channel_user_mtm" to "authenticated";

grant references on table "public"."channel_user_mtm" to "authenticated";

grant select on table "public"."channel_user_mtm" to "authenticated";

grant trigger on table "public"."channel_user_mtm" to "authenticated";

grant truncate on table "public"."channel_user_mtm" to "authenticated";

grant update on table "public"."channel_user_mtm" to "authenticated";

grant delete on table "public"."channel_user_mtm" to "service_role";

grant insert on table "public"."channel_user_mtm" to "service_role";

grant references on table "public"."channel_user_mtm" to "service_role";

grant select on table "public"."channel_user_mtm" to "service_role";

grant trigger on table "public"."channel_user_mtm" to "service_role";

grant truncate on table "public"."channel_user_mtm" to "service_role";

grant update on table "public"."channel_user_mtm" to "service_role";

grant delete on table "public"."customer_rating" to "anon";

grant insert on table "public"."customer_rating" to "anon";

grant references on table "public"."customer_rating" to "anon";

grant select on table "public"."customer_rating" to "anon";

grant trigger on table "public"."customer_rating" to "anon";

grant truncate on table "public"."customer_rating" to "anon";

grant update on table "public"."customer_rating" to "anon";

grant delete on table "public"."customer_rating" to "authenticated";

grant insert on table "public"."customer_rating" to "authenticated";

grant references on table "public"."customer_rating" to "authenticated";

grant select on table "public"."customer_rating" to "authenticated";

grant trigger on table "public"."customer_rating" to "authenticated";

grant truncate on table "public"."customer_rating" to "authenticated";

grant update on table "public"."customer_rating" to "authenticated";

grant delete on table "public"."customer_rating" to "service_role";

grant insert on table "public"."customer_rating" to "service_role";

grant references on table "public"."customer_rating" to "service_role";

grant select on table "public"."customer_rating" to "service_role";

grant trigger on table "public"."customer_rating" to "service_role";

grant truncate on table "public"."customer_rating" to "service_role";

grant update on table "public"."customer_rating" to "service_role";

grant delete on table "public"."fliiinker_config" to "anon";

grant insert on table "public"."fliiinker_config" to "anon";

grant references on table "public"."fliiinker_config" to "anon";

grant select on table "public"."fliiinker_config" to "anon";

grant trigger on table "public"."fliiinker_config" to "anon";

grant truncate on table "public"."fliiinker_config" to "anon";

grant update on table "public"."fliiinker_config" to "anon";

grant delete on table "public"."fliiinker_config" to "authenticated";

grant insert on table "public"."fliiinker_config" to "authenticated";

grant references on table "public"."fliiinker_config" to "authenticated";

grant select on table "public"."fliiinker_config" to "authenticated";

grant trigger on table "public"."fliiinker_config" to "authenticated";

grant truncate on table "public"."fliiinker_config" to "authenticated";

grant update on table "public"."fliiinker_config" to "authenticated";

grant delete on table "public"."fliiinker_config" to "service_role";

grant insert on table "public"."fliiinker_config" to "service_role";

grant references on table "public"."fliiinker_config" to "service_role";

grant select on table "public"."fliiinker_config" to "service_role";

grant trigger on table "public"."fliiinker_config" to "service_role";

grant truncate on table "public"."fliiinker_config" to "service_role";

grant update on table "public"."fliiinker_config" to "service_role";

grant delete on table "public"."fliiinker_profile" to "anon";

grant insert on table "public"."fliiinker_profile" to "anon";

grant references on table "public"."fliiinker_profile" to "anon";

grant select on table "public"."fliiinker_profile" to "anon";

grant trigger on table "public"."fliiinker_profile" to "anon";

grant truncate on table "public"."fliiinker_profile" to "anon";

grant update on table "public"."fliiinker_profile" to "anon";

grant delete on table "public"."fliiinker_profile" to "authenticated";

grant insert on table "public"."fliiinker_profile" to "authenticated";

grant references on table "public"."fliiinker_profile" to "authenticated";

grant select on table "public"."fliiinker_profile" to "authenticated";

grant trigger on table "public"."fliiinker_profile" to "authenticated";

grant truncate on table "public"."fliiinker_profile" to "authenticated";

grant update on table "public"."fliiinker_profile" to "authenticated";

grant delete on table "public"."fliiinker_profile" to "service_role";

grant insert on table "public"."fliiinker_profile" to "service_role";

grant references on table "public"."fliiinker_profile" to "service_role";

grant select on table "public"."fliiinker_profile" to "service_role";

grant trigger on table "public"."fliiinker_profile" to "service_role";

grant truncate on table "public"."fliiinker_profile" to "service_role";

grant update on table "public"."fliiinker_profile" to "service_role";

grant delete on table "public"."fliiinker_rating" to "anon";

grant insert on table "public"."fliiinker_rating" to "anon";

grant references on table "public"."fliiinker_rating" to "anon";

grant select on table "public"."fliiinker_rating" to "anon";

grant trigger on table "public"."fliiinker_rating" to "anon";

grant truncate on table "public"."fliiinker_rating" to "anon";

grant update on table "public"."fliiinker_rating" to "anon";

grant delete on table "public"."fliiinker_rating" to "authenticated";

grant insert on table "public"."fliiinker_rating" to "authenticated";

grant references on table "public"."fliiinker_rating" to "authenticated";

grant select on table "public"."fliiinker_rating" to "authenticated";

grant trigger on table "public"."fliiinker_rating" to "authenticated";

grant truncate on table "public"."fliiinker_rating" to "authenticated";

grant update on table "public"."fliiinker_rating" to "authenticated";

grant delete on table "public"."fliiinker_rating" to "service_role";

grant insert on table "public"."fliiinker_rating" to "service_role";

grant references on table "public"."fliiinker_rating" to "service_role";

grant select on table "public"."fliiinker_rating" to "service_role";

grant trigger on table "public"."fliiinker_rating" to "service_role";

grant truncate on table "public"."fliiinker_rating" to "service_role";

grant update on table "public"."fliiinker_rating" to "service_role";

grant delete on table "public"."fliiinker_service_mtm" to "anon";

grant insert on table "public"."fliiinker_service_mtm" to "anon";

grant references on table "public"."fliiinker_service_mtm" to "anon";

grant select on table "public"."fliiinker_service_mtm" to "anon";

grant trigger on table "public"."fliiinker_service_mtm" to "anon";

grant truncate on table "public"."fliiinker_service_mtm" to "anon";

grant update on table "public"."fliiinker_service_mtm" to "anon";

grant delete on table "public"."fliiinker_service_mtm" to "authenticated";

grant insert on table "public"."fliiinker_service_mtm" to "authenticated";

grant references on table "public"."fliiinker_service_mtm" to "authenticated";

grant select on table "public"."fliiinker_service_mtm" to "authenticated";

grant trigger on table "public"."fliiinker_service_mtm" to "authenticated";

grant truncate on table "public"."fliiinker_service_mtm" to "authenticated";

grant update on table "public"."fliiinker_service_mtm" to "authenticated";

grant delete on table "public"."fliiinker_service_mtm" to "service_role";

grant insert on table "public"."fliiinker_service_mtm" to "service_role";

grant references on table "public"."fliiinker_service_mtm" to "service_role";

grant select on table "public"."fliiinker_service_mtm" to "service_role";

grant trigger on table "public"."fliiinker_service_mtm" to "service_role";

grant truncate on table "public"."fliiinker_service_mtm" to "service_role";

grant update on table "public"."fliiinker_service_mtm" to "service_role";

grant delete on table "public"."fliiinker_service_rating" to "anon";

grant insert on table "public"."fliiinker_service_rating" to "anon";

grant references on table "public"."fliiinker_service_rating" to "anon";

grant select on table "public"."fliiinker_service_rating" to "anon";

grant trigger on table "public"."fliiinker_service_rating" to "anon";

grant truncate on table "public"."fliiinker_service_rating" to "anon";

grant update on table "public"."fliiinker_service_rating" to "anon";

grant delete on table "public"."fliiinker_service_rating" to "authenticated";

grant insert on table "public"."fliiinker_service_rating" to "authenticated";

grant references on table "public"."fliiinker_service_rating" to "authenticated";

grant select on table "public"."fliiinker_service_rating" to "authenticated";

grant trigger on table "public"."fliiinker_service_rating" to "authenticated";

grant truncate on table "public"."fliiinker_service_rating" to "authenticated";

grant update on table "public"."fliiinker_service_rating" to "authenticated";

grant delete on table "public"."fliiinker_service_rating" to "service_role";

grant insert on table "public"."fliiinker_service_rating" to "service_role";

grant references on table "public"."fliiinker_service_rating" to "service_role";

grant select on table "public"."fliiinker_service_rating" to "service_role";

grant trigger on table "public"."fliiinker_service_rating" to "service_role";

grant truncate on table "public"."fliiinker_service_rating" to "service_role";

grant update on table "public"."fliiinker_service_rating" to "service_role";

grant delete on table "public"."linking" to "anon";

grant insert on table "public"."linking" to "anon";

grant references on table "public"."linking" to "anon";

grant select on table "public"."linking" to "anon";

grant trigger on table "public"."linking" to "anon";

grant truncate on table "public"."linking" to "anon";

grant update on table "public"."linking" to "anon";

grant delete on table "public"."linking" to "authenticated";

grant insert on table "public"."linking" to "authenticated";

grant references on table "public"."linking" to "authenticated";

grant select on table "public"."linking" to "authenticated";

grant trigger on table "public"."linking" to "authenticated";

grant truncate on table "public"."linking" to "authenticated";

grant update on table "public"."linking" to "authenticated";

grant delete on table "public"."linking" to "service_role";

grant insert on table "public"."linking" to "service_role";

grant references on table "public"."linking" to "service_role";

grant select on table "public"."linking" to "service_role";

grant trigger on table "public"."linking" to "service_role";

grant truncate on table "public"."linking" to "service_role";

grant update on table "public"."linking" to "service_role";

grant delete on table "public"."linking_event" to "anon";

grant insert on table "public"."linking_event" to "anon";

grant references on table "public"."linking_event" to "anon";

grant select on table "public"."linking_event" to "anon";

grant trigger on table "public"."linking_event" to "anon";

grant truncate on table "public"."linking_event" to "anon";

grant update on table "public"."linking_event" to "anon";

grant delete on table "public"."linking_event" to "authenticated";

grant insert on table "public"."linking_event" to "authenticated";

grant references on table "public"."linking_event" to "authenticated";

grant select on table "public"."linking_event" to "authenticated";

grant trigger on table "public"."linking_event" to "authenticated";

grant truncate on table "public"."linking_event" to "authenticated";

grant update on table "public"."linking_event" to "authenticated";

grant delete on table "public"."linking_event" to "service_role";

grant insert on table "public"."linking_event" to "service_role";

grant references on table "public"."linking_event" to "service_role";

grant select on table "public"."linking_event" to "service_role";

grant trigger on table "public"."linking_event" to "service_role";

grant truncate on table "public"."linking_event" to "service_role";

grant update on table "public"."linking_event" to "service_role";

grant delete on table "public"."message_chat" to "anon";

grant insert on table "public"."message_chat" to "anon";

grant references on table "public"."message_chat" to "anon";

grant select on table "public"."message_chat" to "anon";

grant trigger on table "public"."message_chat" to "anon";

grant truncate on table "public"."message_chat" to "anon";

grant update on table "public"."message_chat" to "anon";

grant delete on table "public"."message_chat" to "authenticated";

grant insert on table "public"."message_chat" to "authenticated";

grant references on table "public"."message_chat" to "authenticated";

grant select on table "public"."message_chat" to "authenticated";

grant trigger on table "public"."message_chat" to "authenticated";

grant truncate on table "public"."message_chat" to "authenticated";

grant update on table "public"."message_chat" to "authenticated";

grant delete on table "public"."message_chat" to "service_role";

grant insert on table "public"."message_chat" to "service_role";

grant references on table "public"."message_chat" to "service_role";

grant select on table "public"."message_chat" to "service_role";

grant trigger on table "public"."message_chat" to "service_role";

grant truncate on table "public"."message_chat" to "service_role";

grant update on table "public"."message_chat" to "service_role";

grant delete on table "public"."order" to "anon";

grant insert on table "public"."order" to "anon";

grant references on table "public"."order" to "anon";

grant select on table "public"."order" to "anon";

grant trigger on table "public"."order" to "anon";

grant truncate on table "public"."order" to "anon";

grant update on table "public"."order" to "anon";

grant delete on table "public"."order" to "authenticated";

grant insert on table "public"."order" to "authenticated";

grant references on table "public"."order" to "authenticated";

grant select on table "public"."order" to "authenticated";

grant trigger on table "public"."order" to "authenticated";

grant truncate on table "public"."order" to "authenticated";

grant update on table "public"."order" to "authenticated";

grant delete on table "public"."order" to "service_role";

grant insert on table "public"."order" to "service_role";

grant references on table "public"."order" to "service_role";

grant select on table "public"."order" to "service_role";

grant trigger on table "public"."order" to "service_role";

grant truncate on table "public"."order" to "service_role";

grant update on table "public"."order" to "service_role";

grant delete on table "public"."order_metadata" to "anon";

grant insert on table "public"."order_metadata" to "anon";

grant references on table "public"."order_metadata" to "anon";

grant select on table "public"."order_metadata" to "anon";

grant trigger on table "public"."order_metadata" to "anon";

grant truncate on table "public"."order_metadata" to "anon";

grant update on table "public"."order_metadata" to "anon";

grant delete on table "public"."order_metadata" to "authenticated";

grant insert on table "public"."order_metadata" to "authenticated";

grant references on table "public"."order_metadata" to "authenticated";

grant select on table "public"."order_metadata" to "authenticated";

grant trigger on table "public"."order_metadata" to "authenticated";

grant truncate on table "public"."order_metadata" to "authenticated";

grant update on table "public"."order_metadata" to "authenticated";

grant delete on table "public"."order_metadata" to "service_role";

grant insert on table "public"."order_metadata" to "service_role";

grant references on table "public"."order_metadata" to "service_role";

grant select on table "public"."order_metadata" to "service_role";

grant trigger on table "public"."order_metadata" to "service_role";

grant truncate on table "public"."order_metadata" to "service_role";

grant update on table "public"."order_metadata" to "service_role";

grant delete on table "public"."public_profile" to "anon";

grant insert on table "public"."public_profile" to "anon";

grant references on table "public"."public_profile" to "anon";

grant select on table "public"."public_profile" to "anon";

grant trigger on table "public"."public_profile" to "anon";

grant truncate on table "public"."public_profile" to "anon";

grant update on table "public"."public_profile" to "anon";

grant delete on table "public"."public_profile" to "authenticated";

grant insert on table "public"."public_profile" to "authenticated";

grant references on table "public"."public_profile" to "authenticated";

grant select on table "public"."public_profile" to "authenticated";

grant trigger on table "public"."public_profile" to "authenticated";

grant truncate on table "public"."public_profile" to "authenticated";

grant update on table "public"."public_profile" to "authenticated";

grant delete on table "public"."public_profile" to "service_role";

grant insert on table "public"."public_profile" to "service_role";

grant references on table "public"."public_profile" to "service_role";

grant select on table "public"."public_profile" to "service_role";

grant trigger on table "public"."public_profile" to "service_role";

grant truncate on table "public"."public_profile" to "service_role";

grant update on table "public"."public_profile" to "service_role";

grant delete on table "public"."search" to "anon";

grant insert on table "public"."search" to "anon";

grant references on table "public"."search" to "anon";

grant select on table "public"."search" to "anon";

grant trigger on table "public"."search" to "anon";

grant truncate on table "public"."search" to "anon";

grant update on table "public"."search" to "anon";

grant delete on table "public"."search" to "authenticated";

grant insert on table "public"."search" to "authenticated";

grant references on table "public"."search" to "authenticated";

grant select on table "public"."search" to "authenticated";

grant trigger on table "public"."search" to "authenticated";

grant truncate on table "public"."search" to "authenticated";

grant update on table "public"."search" to "authenticated";

grant delete on table "public"."search" to "service_role";

grant insert on table "public"."search" to "service_role";

grant references on table "public"."search" to "service_role";

grant select on table "public"."search" to "service_role";

grant trigger on table "public"."search" to "service_role";

grant truncate on table "public"."search" to "service_role";

grant update on table "public"."search" to "service_role";

grant delete on table "public"."service" to "anon";

grant insert on table "public"."service" to "anon";

grant references on table "public"."service" to "anon";

grant select on table "public"."service" to "anon";

grant trigger on table "public"."service" to "anon";

grant truncate on table "public"."service" to "anon";

grant update on table "public"."service" to "anon";

grant delete on table "public"."service" to "authenticated";

grant insert on table "public"."service" to "authenticated";

grant references on table "public"."service" to "authenticated";

grant select on table "public"."service" to "authenticated";

grant trigger on table "public"."service" to "authenticated";

grant truncate on table "public"."service" to "authenticated";

grant update on table "public"."service" to "authenticated";

grant delete on table "public"."service" to "service_role";

grant insert on table "public"."service" to "service_role";

grant references on table "public"."service" to "service_role";

grant select on table "public"."service" to "service_role";

grant trigger on table "public"."service" to "service_role";

grant truncate on table "public"."service" to "service_role";

grant update on table "public"."service" to "service_role";

grant delete on table "public"."user_search_mtm" to "anon";

grant insert on table "public"."user_search_mtm" to "anon";

grant references on table "public"."user_search_mtm" to "anon";

grant select on table "public"."user_search_mtm" to "anon";

grant trigger on table "public"."user_search_mtm" to "anon";

grant truncate on table "public"."user_search_mtm" to "anon";

grant update on table "public"."user_search_mtm" to "anon";

grant delete on table "public"."user_search_mtm" to "authenticated";

grant insert on table "public"."user_search_mtm" to "authenticated";

grant references on table "public"."user_search_mtm" to "authenticated";

grant select on table "public"."user_search_mtm" to "authenticated";

grant trigger on table "public"."user_search_mtm" to "authenticated";

grant truncate on table "public"."user_search_mtm" to "authenticated";

grant update on table "public"."user_search_mtm" to "authenticated";

grant delete on table "public"."user_search_mtm" to "service_role";

grant insert on table "public"."user_search_mtm" to "service_role";

grant references on table "public"."user_search_mtm" to "service_role";

grant select on table "public"."user_search_mtm" to "service_role";

grant trigger on table "public"."user_search_mtm" to "service_role";

grant truncate on table "public"."user_search_mtm" to "service_role";

grant update on table "public"."user_search_mtm" to "service_role";


